services:
  - type: web
    name: paperandprose
    runtime: dotnet
    repo: https://github.com/K-Town182/PaperAndProse
    branch: main
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/PaperAndProse.dll
    region: oregon
    plan: free